name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    #- name: configure
    #  run: ./configure
    #We do not have a configure file as of now
    - name: make
      run: make
    #- name: make distcheck
    #  run: make distcheck

